import type { Metadata } from "next";
import "./globals.css";
import { Golos_Text } from "next/font/google";
import { Header } from "@/components/Header";

const golosText = Golos_Text({ subsets: ["latin"], weight: "variable" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${golosText.className} flex justify-center`}>
                <div className="w-full h-screen flex items-center">
                    <div className="max-w-[1158px] w-full items-center p-4">
                        <Header />
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
