import type { Metadata } from "next";
import "./globals.css";
import { Golos_Text } from "next/font/google";

const golosText = Golos_Text({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${golosText.className} max-w-[1200px] mx-auto my-8`}
            >
                {children}
            </body>
        </html>
    );
}
